#!/bin/bash 
set -eu
xtc=$1
top=$2
echo "System" | gmx trjconv -f $xtc -s $top -pbc whole -o tmp.xtc #-tu ns -b 10
gmx trjconv -f tmp.xtc -s $top -o corrected_${xtc} -pbc mol -center -ur compact <<EOF
Protein
System
EOF
rm tmp.xtc
