#!/bin/bash
set -Ceu

#http://manual.gromacs.org/documentation/2018/onlinehelp/gmx-trjconv.html
#compact puts all atoms at the closest distance from the center of the box. 
#This can be useful for visualizing e.g. truncated octahedra or rhombic dodecahedra.

cat <<EOF

Usage:
    $0 [TRJ_FILE (.xtc)] [TOP_FILE (.pdb, .gro, or .tpr)] [NSKIP (integer)] [OUT_FORMAT (.pdb, .gro, .xtc, trr)]

NOTE:
    This script may not work for multimer systems.
    e.g. a tetramer of streptavidin.

EOF

TRJ=$1
TOP=$2
nskips=$3
fmt=$4
bn=$(basename ${TRJ})
OUTNAME=${bn%.*}.${fmt}

echo "INP: $TRJ"
echo "TOP: $TOP"
echo "OUTNAME: $OUTNAME"
#read -p "OK? [Enter]"

echo System | gmx trjconv -s $TOP \
                          -f ${TRJ} \
                          -o ${OUTNAME} \
                          -pbc whole \
                          -skip ${nskips} \
                          -tu ns

echo Protein System | gmx trjconv -s $TOP \
                       -f ${OUTNAME} \
                       -o ${OUTNAME} \
                       -pbc cluster

echo Protein System | gmx trjconv -s $TOP \
                       -f ${OUTNAME} \
                       -o ${OUTNAME} \
                       -pbc res -ur compact -center

echo Protein System | gmx trjconv -s ${TOP} \
                       -f ${OUTNAME} \
                       -o ${OUTNAME} \
                       -fit rot+trans
rm \#*
