#!/bin/bash
set -Ceu
cat<<EOS

Usage:
    $0 [FULL PATH to a directory including *.xtc and em2.tpr ]

Note: 
    This program accepts only the full path. 
    
EOS
SCRIPT="/Users/siida/Dropbox/01code/software/myTools/for_gromacs/script/groCorrPBC"

readonly TRAJ_DIR="corrected_traj_data"
readonly PATH_TO_ORIG_TRAJ=$1
readonly PREFIX='npt_prod'

cat<<EOS
I'm going to create ${TRAJ_DIR}. 
EOS
read -p "How many trajectories you are going to process? : " n_runs

mkdir ${TRAJ_DIR}
cd ${TRAJ_DIR}
mkdir system 
cd system

for (( i=0; i<${n_runs}; i++ )); do
    ${SCRIPT} ${PATH_TO_ORIG_TRAJ}/${PREFIX}_${i}.xtc ${PATH_TO_ORIG_TRAJ}/em2.tpr 1 xtc
done

cd -
